### ISSUE TITLE
Podcatcher crashes immediately

### ISSUE THREAD

**Issue by stevelitchfield** [kypeli/Podcatcher#20] opened 2013-01-27 20:58 UTC
Latest beta (today). Works ok, but then after switching away from the app, whenever I try and tap on the Podcatcher icon on the app menu, the app crashes immediately. No error message,

Problem clears up after restarting the phone.

This on the Lumia 920.

**Comment by kypeli** [comment] 2013-01-28 05:05
Thanks Steve for writing this bug down! I would say this is one issue I've heard from other places as well, but seems to be happening only on WP8 :-/ So I haven't been able to reproduce it myself yet.

Any additional info, like some steps or actions you recall taking prior to this happening would also be highly appreciated.

**Comment by stevelitchfield** [comment] 2013-01-28 07:29
Actually, having restarted my Lumia 920, Podcatcher beta now won't even launch at all. Ever.

Is there a log file or similar that it generates that I can send to you?

**Comment by kypeli** [comment] 2013-01-28 07:31
I think this is valuable information! :) I have tried to reproduce this exact crash with WP7 and the WP8 without success. 

I think the device will automatically send crash reports to my Windows Phone developer page for Podcatcher, so I should be able to see them there. If I may ask, can you please restart/crash the app a few more times so I can see these crashes for this version in the statistics - and then hopefully be able to find out what's going on.

Unfortunately that's the only way I know of how to send logs if you don't have the source code and launch the app from Visual Studio :-(

**Comment by stevelitchfield** [comment] 2013-01-28 07:33
Did it five times just now. No idea if your app was alive long enough to send messages out though?

**Comment by kypeli** [comment] 2013-01-28 07:35
...and the logs are a couple of days behind, so I guess I will find out the day after tomorrow :-/

Oh, btw. did you update the app and then it started to crash? This is a known issue as I changed the DB layout so you need to do a fresh install. Could the crashes be b/c of this?

**Comment by stevelitchfield** [comment] 2013-01-28 08:01
I'll remove and re-install... Presume I can do so from your original beta email link....
[time passes]
Ah yes, Podcatcher works now. Phew! How will you handle people upgrading from the old stable release, eventually? Can you warn people to export their feeds, uninstall, then re-install to get the new, stable version? 

Also, sorry if I'm being stupid, but there's no way to pick up gpodder feeds or import feeds from SkyDrive - have you taken these out? At the moment, upgraders have to remember, search for, or enter every single feed all over again....

**Comment by kypeli** [comment] 2013-01-28 08:06
The update will work for non-beta users; all DB changes will be done in one sequence, while in this beta the changes are added incrementally (and these smaller increments are not handled in the betas). So I will for sure test and ensure that updating from 2.1.0.0 to 2.2.0.0 will work :) 

If you have set up your feeds in gPodder.net, you should be able to import them as well. Or what do you mean? At this moment I don't have plans to add SkyDrive import as that would require a SkyDrive file browser which I don't intend to build myself :) If there's a ready-made component for this, then adding this would be not an issue. I haven't yet looked very thoroughly for one yet... 

But I guess I can close this issue for now, if the reason was that you updated the beta version and there was a mismatch in the database schemes?

**Comment by stevelitchfield** [comment] 2013-01-28 12:38
Yes, close it for now. I've also found the gPodder import scrreen - I hadn't swiped far enough etc [blush].

Oops! Keep up the good work!

**Comment by kypeli** [comment] 2013-01-28 12:41
Good to know! Thanks! :)

**Closed as completed by kypeli** 2013-01-28 12:41 UTC
